### ISSUE TITLE
Make default branch name editable

### ISSUE THREAD

**Issue by duvalbruno** [PsykoSoldi3r/vscode-git-flow#12]
with the trend of changing the default branch name from **trunk** to **master** to **main**, the extension does not work on repo where the default branch name is not master.

https://github.com/PsykoSoldi3r/vscode-git-flow/blob/87a16f17400ddbf92b7e464fdcd5dd3c915330df/src/services/GitService.ts#L61

**Comment by Serhioromano** [comment]
I think you can run `git flow init -f` command to change it.
