### ISSUE TITLE
Features are not displayed in VSC insider

### ISSUE THREAD

**Issue by darkpio** [PsykoSoldi3r/vscode-git-flow#2]
When I am on a project in VSC insider I can see on Git Flow on the top my master and develop branch.
When I click on + in Features, I can create a feature. I push the feature but still, nothing appears under the FEATURES, even after a refresh or restart VSC.

Git flow v0.4.0
vsc 1.46.0

**Comment by PsykoSoldi3r** [comment]
Could you check if there is any errors logged in the Output of Git Flow after creating the feature?

**Comment by darkpio** [comment]
Hi,
"
git config gitflow.branch.master
git config gitflow.branch.develop
git config gitflow.prefix.feature
git config gitflow.prefix.release
git config gitflow.prefix.hotfix
git config gitflow.prefix.support
git config gitflow.prefix.versiontag
git config gitflow.branch.master
git config gitflow.branch.develop
git config gitflow.prefix.feature
git config gitflow.prefix.release
git config gitflow.prefix.hotfix
git config gitflow.prefix.support
git config gitflow.prefix.versiontag
git branch
git branch
git branch
git branch --all
git flow feature start editBoard
git branch
git branch
"

**Comment by darkpio** [comment]
Take the time for a coffee ^^
You get 3,00 EUR

**Comment by PsykoSoldi3r** [comment]
Thanks for the coffee 😁

I try to reproduce the issue but I can push the new created branches with the + feature on VS Insides 1.46.0 and the feature is shown in the list.

What is gitflow.prefix.feature set in the config?  Please run `git config gitflow.prefix.feature` in the terminal in your git repository folder.

**Comment by PsykoSoldi3r** [comment]
I have published a new version 0.4.1 to the marketplace. In this version I made a change to the logging. The git commands now will log all outputs not only errors.

I also had to make a change into code by a breaking change in vscode. The fire event of an event emitter for refreshing needs a paramater. I have resolved this issue. This could resolve your issue as well. Could you please check this for me?

Thanks

**Comment by darkpio** [comment]
![after](https://user-images.githubusercontent.com/10997358/82253004-6b02cb00-9950-11ea-916f-1cb373e83f80.jpg)
![before](https://user-images.githubusercontent.com/10997358/82253007-6b02cb00-9950-11ea-9409-f14532b2abe0.jpg)

**Comment by PsykoSoldi3r** [comment]
The defaults settings in git flow is that the prefix of a feature is feature/ and not feature_. The list properly only supports the feature/ and should also support the one is set in the config.

I'm on it!

**Comment by PsykoSoldi3r** [comment]
Fixed and publish to marketplace as v0.4.2

Thank you @darkpio, it was a great coffee! ☕️😁

**Comment by darkpio** [comment]
It works. Really good add on. Thank you.
