### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by franzmaster** [PsykoSoldi3r/vscode-git-flow#3]
- Issue Type: `Performance`
- Extension Name: `vscode-git-flow`
- Extension Version: `0.4.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\franz\PsykoSoldi3r.vscode-git-flow-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by PsykoSoldi3r** [comment]
I don't see any high cpu load on my extension (on Mac).

Could you send me please the cpuprofile.txt file? So I can take a look where it goes wrong.

**Comment by PsykoSoldi3r** [comment]
@franzmaster Could you provide me the cpuprofile.txt so I can take a look where the CPU hiccups are?

**Comment by PsykoSoldi3r** [comment]
Closed due inactivity
