### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tomtastico** [PsykoSoldi3r/vscode-git-flow#5]
Thanks for this extension! I see it has not been worked on for a while, but leaving this issue here just in case you get back to it :)

The extension takes a long time to load in Windows. It also takes a long time to start a new feature (I suppose for the same reason the initial load takes long).

I have a lot of existing git flow feature branches (around 130), not sure if that's a factor.

- Issue Type: `Performance`
- Extension Name: `vscode-git-flow`
- Extension Version: `0.4.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
[PsykoSoldi3r.vscode-git-flow-unresponsive.cpuprofile.txt](https://github.com/PsykoSoldi3r/vscode-git-flow/files/5981536/PsykoSoldi3r.vscode-git-flow-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tomtastico** [comment]
@PsykoSoldi3r I think I found a solution for this, please check the MR and hopefully it will be fine and you can do a new release! I

**Comment by PsykoSoldi3r** [comment]
@tomtastico Thank you very much! Pull request is merged and published to marketplace with version 0.5.0
