### ISSUE TITLE
Please add to Open VSX registry

### ISSUE THREAD

**Issue by BrianGilbert** [PsykoSoldi3r/vscode-git-flow#9]
https://open-vsx.org/

The Open VSX Registry offers a community driven, fully open platform for publishing and consuming VS Code extensions. The Registry is built on Eclipse Open VSX, which is an open source project hosted at the Eclipse Foundation.

Open VSX is integrated into multiple software applications that support VS Code extensions. There is strong demand for a fully open alternative to the Visual Studio Marketplace, and with hundreds of great extensions already available, it is the intent of the Eclipse Foundation to enable continued and accelerated growth.

**Comment by Serhioromano** [comment]
Please explain why there is a demand to multiply marketplaces. It is pointless in my view. Why? It is much simpler to search for extension in one place than in 2 places.

**Comment by joeykamsteeg** [comment]
I totally agree with @Serhioromano, but If there are more people who wants to have it on Open VSX we could decide to also publish this extension to Open VSX

**Comment by Serhioromano** [comment]
@PsykoSoldi3r @BrianGilbert I'll never publish my extensions to another repository. I'll not turn my extension delivery into delivery hell. I am not alon on that I think. So Microsoft market place will always have all the extensions anyway and alternative only some of them.

This idea would make some sense, if for instance Microsoft created a rule that do not allow some developers to publish extensions, and the only way to install those extensions is manual download and installation with CLI, then that would make a lot of sense to create a repository with all those extensions.
